### ISSUE TITLE
E21 Favor Composition over Inheritance 

### ISSUE THREAD

**Issue by martinmarth** [BlazingTwist/Clean-Code-Development-Jchess#1]
> Examine the Java Open Chess code base and make yourself familiar with the current inheritance hierarchy. Find
and discuss in your team where applying the principle of favoring composition over inheritance would lead to a
better design.

**Comment by BlazingTwist** [comment]
As far as I can tell, the only occurrence of Inheritance that we can eliminate is the chess pieces. (`abstract class Piece`).
The other occurrences of inheritance are the GUI (e.g. `extends JPanel`) which we cannot avoid due to how the GUI Framework works.

A preliminary checklist might look like this:
- [ ] create a package for the chess pieces (e.g. `jchess.piece`)
- [ ] decompose the abstract class `Piece` into one or more Interfaces
- [ ] Migrate the pieces one-by-one into the new package

**Comment by martinmarth** [comment]
I would propose something like this:

```
public interface ChessPieceBehavior {

    enum PieceName {
        BISHOP,
        KING,
        KNIGHT,
        PAWN,
        QUEEN,
        ROOK
    }

    ArrayList<Square> allMoves();
    String getSymbol();
    Image getImage();
    PieceName getName();
    boolean isOutOfBounds(int x, int y);
    boolean canMoveTo(int x, int y);
    boolean otherOwner(int x, int y);
}
```
Each type of chess piece would need to implement this interface in a separate class. (e.g: `PawnBehavior`)
Additionally we would have a single `Piece` class looking somewhat like this:

```
public class Piece {
    private final ChessPieceBehavior behavior;

    public Piece(ChessPieceBehavior behavior, Chessboard chessboard, Player player) {
        this.behavior = behavior;
        ...
    }

    public void draw(Graphics g) {
       ...
    }

    public String getSymbol() {
        return behavior.getSymbol();
    }

}
```

We could also add an `AbstractChessPieceBehavior` class that would implement methods that are common among all `ChessPieceBehaviors`. That will probably include all methods except `allMoves()`.  

In the End we could create a Pawn (for example) like this:
```
ChessPieceBehavior pawnBehavior = new PawnBehavior(chessboard, player);
Piece pawn = new Piece(pawnBehavior);
```

What are your thoughts about this approach? @BlazingTwist  @avl1708  @xJxAxNx
